### ISSUE TITLE
567.42->伍佰陆拾柒圆肆角壹分

### ISSUE THREAD

**Issue by WalkerDenial** [yourtion/Alfred_NumToCny#6]
最后应该是**贰分**，不是**壹分**

**Comment by yourtion** [comment]
请升级到最新版本，这个问题应该是已经解决。https://github.com/yourtion/Alfred_NumToCny/releases/tag/1.4

![screen shot 2016-12-10 at 6 52 19 pm](https://cloud.githubusercontent.com/assets/1475301/21072822/e0cf43a6-bf09-11e6-8bd6-92791d19be9e.png)
